import type { Metadata } from "next";
import { Elsie, DM_Sans } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layouts/Layout";
import { Toaster } from "@/components/ui/sonner";

const fontElsie = Elsie({
  subsets: ["latin"],
  variable: "--font-elsie",
  weight: ["400", "900"],
});
const fontDMSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${fontElsie.variable} ${fontDMSans.variable} antialiased`}
      >
        <Layout>{children}</Layout>
        <Toaster position='top-center' richColors />
      </body>
    </html>
  );
}
